### ISSUE TITLE
Error Updating Submodule

### ISSUE THREAD

**Issue by ibnAbuMahdi** [tohenk/php-dpfb-demo#1]
While trying to run "git submodule update --merge --remote -- www/cdn" I got "fatal: could not get a repository handle for submodule 'www/cdn'"

**Comment by tohenk** [comment]
You may need to init the submodule once `git submodule update --init --merge --remote -- www/cdn`.

**Comment by ibnAbuMahdi** [comment]
I got "could not get a repository handle for submodule 'www/cdn'" error

**Comment by ibnAbuMahdi** [comment]
Problem Solved! I had to clone the submodule repo into www/cdn first and then ran the update command

**Comment by ibnAbuMahdi** [comment]
Thank you Mr Toha for this project

**Comment by tohenk** [comment]
Updated README.
